export const ADD_INDEX = 'addIndex'
export const REDUCE_INDEX = 'reduceIndex'
export const CHOOSED_NUMBER = 'choosedNumber'
export const SET_JUDGEMENT = 'setJudgement'
export const SET_FIRST_ANSWER = 'setFirstAnswer'
export const SET_OLD_ANSWER = 'setOldAnswer'
export const SET_TEST_AGAIN = 'setTestAgain'
export const CHANGE_USER_NAME = 'changeUserName'
